export const REGISTER_EMPLOYEE_SUCCESS = 'REGISTER_EMPLOYEE_SUCCESS';
export const REGISTER_EMPLOYER_SUCCESS = 'REGISTER_EMPLOYER_SUCCESS';

export const REGISTER_EMPLOYEE_START = 'REGISTER_EMPLOYEE_START';
export const REGISTER_EMPLOYEE_PROCEED = 'REGISTER_EMPLOYEE_PROCEED';
export const REGISTER_EMPLOYEE_SKIP = 'REGISTER_EMPLOYEE_SKIP';
export const REGISTER_EMPLOYEE_COMPLETE = 'REGISTER_EMPLOYEE_COMPLETE';

export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';
